/* eslint-disable */
"use client";

import { useState, useEffect } from "react";
import { FileText, Database, X, ChevronRight, Loader2 } from "lucide-react";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

const API_BASE = "http://localhost:8000/api";

export default function ReportsLibrary() {
  const [reports, setReports] = useState<{filename: string, modified: number, size: number}[]>([]);
  const [selectedReport, setSelectedReport] = useState<string | null>(null);
  const [reportContent, setReportContent] = useState<string>("");
  const [loading, setLoading] = useState(true);

  const fetchReportsList = async () => {
    try {
      const res = await fetch(`${API_BASE}/reports`);
      const data = await res.json();
      setReports(data || []);
    } catch (e) {
      console.error("Could not fetch reports", e);
    } finally {
      setLoading(false);
    }
  };

  const viewReport = async (filename: string) => {
    setSelectedReport(filename);
    try {
      const res = await fetch(`${API_BASE}/reports/${filename}`);
      const data = await res.json();
      setReportContent(data.content || "Report is empty.");
    } catch (e) {
      setReportContent("Failed to load report content.");
    }
  };

  useEffect(() => {
    fetchReportsList();
  }, []);

  useEffect(() => {
    if (selectedReport && reportContent) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = '';
    }
    return () => { document.body.style.overflow = ''; };
  }, [selectedReport, reportContent]);

  return (
    <div className="flex-1 w-full max-w-7xl mx-auto px-4 sm:px-8 py-8 animate-in fade-in duration-500">
      <header className="flex items-center justify-between pb-6 mb-6 border-b border-border/40">
        <div>
          <h1 className="text-2xl font-bold tracking-tight flex items-center gap-2">
            <FileText className="text-purple-500" />
            AI Reports Library
          </h1>
          <p className="text-sm text-muted-foreground mt-1">Deep research markdown reports generated by the analysis bots.</p>
        </div>
      </header>

      {loading ? (
        <div className="flex flex-col items-center justify-center py-24 text-muted-foreground gap-4">
          <Loader2 className="w-8 h-8 animate-spin text-purple-500" />
          <p className="text-sm">Loading library...</p>
        </div>
      ) : (
        <Card className="bg-card/40 backdrop-blur-xl border-border/50 shadow-xl max-w-5xl">
          <CardHeader className="pb-3 px-6 pt-6 border-b border-border/40 bg-muted/10">
            <div className="flex items-center gap-2 text-foreground">
              <Database size={16} className="text-muted-foreground" />
              <span className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Available Reports</span>
              <span className="ml-auto text-xs font-medium bg-purple-500/10 text-purple-400 px-2 py-0.5 rounded-full border border-purple-500/20">{reports.length} files</span>
            </div>
          </CardHeader>
          <CardContent className="p-0">
            {reports.length === 0 ? (
              <div className="p-16 text-sm text-muted-foreground italic text-center">No reports generated yet.</div>
            ) : (
              <div className="divide-y divide-border/30">
                {reports.map((r) => {
                  const date = new Date(r.modified * 1000).toLocaleDateString('ko-KR', { year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });
                  const sizeKb = r.size ? `${(r.size / 1024).toFixed(1)} KB` : '';
                  return (
                    <button
                      key={r.filename}
                      onClick={() => viewReport(r.filename)}
                      className="w-full px-6 py-4 text-left hover:bg-white/5 transition-colors flex items-center gap-4 group"
                    >
                      <div className="h-10 w-10 rounded-lg bg-purple-500/10 border border-purple-500/20 flex items-center justify-center flex-shrink-0 group-hover:scale-110 transition-transform">
                        <FileText size={18} className="text-purple-400" />
                      </div>
                      <div className="flex-1 min-w-0">
                        <p className="text-base font-medium truncate text-foreground group-hover:text-purple-400 transition-colors">{r.filename.replace('.md', '')}</p>
                        <p className="text-xs font-mono text-muted-foreground mt-1">{date}{sizeKb && ` · ${sizeKb}`}</p>
                      </div>
                      <ChevronRight size={18} className="text-muted-foreground/30 group-hover:text-foreground transition-colors flex-shrink-0 group-hover:translate-x-1" />
                    </button>
                  );
                })}
              </div>
            )}
          </CardContent>
        </Card>
      )}

      {/* Report Modal Viewer (Notion style) */}
      {selectedReport && reportContent && (
        <div
          className="fixed inset-0 z-50 flex justify-center bg-black/60 backdrop-blur-md sm:p-6"
          onClick={() => { setSelectedReport(null); setReportContent(''); }}
        >
          <div
            className="bg-background border border-border/50 sm:rounded-2xl shadow-2xl w-full max-w-4xl flex flex-col h-full sm:h-auto sm:max-h-[90vh] animate-in slide-in-from-bottom-4 duration-300"
            onClick={e => e.stopPropagation()}
          >
            {/* Modal Header */}
            <div className="flex items-center justify-between px-6 py-4 border-b border-border/40 bg-card rounded-t-2xl flex-shrink-0">
              <div className="flex items-center gap-3 min-w-0">
                <div className="bg-purple-500/10 p-1.5 rounded-md">
                  <FileText size={16} className="text-purple-400 flex-shrink-0" />
                </div>
                <span className="text-base font-semibold truncate tracking-tight">{selectedReport.replace('.md', '')}</span>
              </div>
              <button
                onClick={() => { setSelectedReport(null); setReportContent(''); }}
                className="ml-4 flex-shrink-0 h-8 w-8 rounded-full flex items-center justify-center hover:bg-muted transition-colors text-muted-foreground hover:text-foreground bg-muted/50"
              >
                <X size={18} />
              </button>
            </div>
            {/* Modal Content */}
            <div className="overflow-y-auto overflow-x-hidden p-6 sm:p-10 scrollbar-thin scrollbar-thumb-border scrollbar-track-transparent">
              <div className="prose prose-zinc dark:prose-invert max-w-none
                prose-headings:font-bold prose-headings:text-foreground prose-headings:tracking-tight
                prose-h1:text-3xl prose-h1:pb-4 prose-h1:border-b prose-h1:border-border/40 prose-h1:mb-6 prose-h1:mt-2
                prose-h2:text-2xl prose-h2:pb-2 prose-h2:border-b prose-h2:border-border/30 prose-h2:mt-10 prose-h2:mb-4
                prose-h3:text-xl prose-h3:mt-8 prose-h3:mb-4
                prose-p:text-[15.5px] prose-p:leading-[1.75] prose-p:my-4 prose-p:text-foreground/90
                prose-a:text-blue-400 hover:prose-a:underline prose-a:no-underline
                prose-blockquote:border-l-[3px] prose-blockquote:border-purple-500/50 prose-blockquote:pl-5 prose-blockquote:text-muted-foreground prose-blockquote:my-6 prose-blockquote:bg-muted/30 prose-blockquote:py-2 prose-blockquote:rounded-r-lg
                prose-table:w-full prose-table:my-6 prose-table:border-collapse
                prose-th:bg-muted/50 prose-th:border-b-2 prose-th:border-border prose-th:px-4 prose-th:py-3 prose-th:font-semibold prose-th:text-left
                prose-td:border-b prose-td:border-border/40 prose-td:px-4 prose-td:py-3
                prose-code:bg-muted prose-code:px-1.5 prose-code:py-0.5 prose-code:rounded-md prose-code:text-foreground prose-code:font-mono prose-code:text-[13px] prose-code:before:content-none prose-code:after:content-none
                prose-pre:bg-[#18181b] prose-pre:border prose-pre:border-border/50 prose-pre:p-5 prose-pre:rounded-xl prose-pre:my-6 prose-pre:overflow-x-auto
                prose-li:my-1.5
              ">
                <ReactMarkdown remarkPlugins={[remarkGfm]}>{reportContent}</ReactMarkdown>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
