from abc import ABC, abstractmethod
from typing import Dict, Any

class IAnalystLLM(ABC):
    """
    Interface for the Analyst LLM (e.g., Claude).
    Responsible for ingesting massive data and outputting a comprehensive Markdown report.
    """
    @abstractmethod
    def analyze(self, code: str, name: str, data: Dict[str, Any]) -> str:
        """
        Analyze the given stock data and produce a detailed Markdown memo.
        
        Args:
            code (str): Stock code.
            name (str): Stock name.
            data (Dict[str, Any]): Raw data including OHLC, Supply, News, Temp, etc.
            
        Returns:
            str: The generated Markdown report.
        """
        pass

class IExecutorLLM(ABC):
    """
    Interface for the Executor LLM (e.g., Claude).
    Responsible for reading the analyst's memo and hard facts, then outputting a strict JSON decision.
    """
    @abstractmethod
    def execute_decision(self, code: str, name: str, memo: str, facts: Dict[str, Any]) -> Dict[str, Any]:
        """
        Produce a strict JSON trading decision based on the memo and hard facts.
        
        Args:
            code (str): Stock code.
            name (str): Stock name.
            memo (str): The markdown report generated by the Analyst LLM.
            facts (Dict[str, Any]): Hard facts (current price, score) for cross-verification.
            
        Returns:
            Dict[str, Any]: Strict JSON parsing containing decision, confidence, target_price, etc.
        """
        pass
