# Korea Investment & Securities (KIS) API Credentials
# Get these from: https://apiportal.koreainvestment.com/
# Copy this file to 'secrets.yaml' and fill in your keys.

CANO: "68024019" # 실전 계좌번호 앞 8자리
ACNT_PRDT_CD: "01" # 계좌번호 뒤 2자리 (보통 01)
PAPER_CANO: "50162351" # 모의투자 계좌번호 앞 8자리

# Real Trading (실전투자)
PROD:
  APP_KEY: "PSc0CxMh7F9TCom24I8Ev6CTTAL5Dy3yfGZa"
  APP_SECRET: "SJGWmtuNgfiOE1kK/q2rUXIbxlRQm+lGJLH55Rl0thO7E93XDTbYrgZSQZwJEjdyQo2slM53CnmldfEd7dDoMqMAByHbiLa5aaURIXkrA/tsbn8d0BMHaHBQ3AIqUHRnCozlWtm+jUrewb34IN6zl5FiJauWbRJeW+Enoa10rbsaaM2yutI="
  URL_BASE: "https://openapi.koreainvestment.com:9443"

# Paper Trading (모의투자)
PAPER:
  APP_KEY: "PSzc8awYRcYrSYfs6gVeMHAISP52lXKXADQJ"
  APP_SECRET: "JcuabNcSgH4AlltTAZAbTkRZUu6lxmzmqj0wtQeXiXA3huKpnQlge1DeREvkiezUKjJWtH4gVMj+FqeRH+nlueHvC3l4QwiZhs/JDawHFw/7kw0efNrfQCE3PLi48pOo2XMnZHbehflhy+RGtt9482LNj9S/iE/7digOP3aCyPJuK2Iup4s="
  URL_BASE: "https://openapivts.koreainvestment.com:29443"

# Common Settings
DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1470676322857779391/aNo1wdAHa41CB7lIoDGB6df9SXVwtAhF1zlYXEof_-QNk7Ax0xQ7ftKBxoj5bYx0sD2e"
DISCORD_SCALP_WEBHOOK_URL: "https://discord.com/api/webhooks/1473883882746282080/yhxpkfm2FWfcrPct2qC_AWqAPElap-v0H5qiK0lS7sisFq8kKu4wJi8haKDI8U_Nn9Y9"
SLACK_WEBHOOK_URL: ""
ANTHROPIC_API_KEY: ""
DART_API_KEY: "97d8e16a229ef4c1bea13de9b2bd4dde13e9e94d"
GEMINI_API_KEY: "AIzaSyBP6KroEDnFDz3np7cBPaeAlKrQ_fc3Nb4"